### ISSUE TITLE
Ps中导出报错

### ISSUE THREAD

**Issue by redasm** [zs9024/quick_psd2ugui#15]
如图
![1547909056 1](https://user-images.githubusercontent.com/9164386/51428240-43a4cc80-1c3c-11e9-9c74-85423d21de6d.png)
命名是不是要区分大小写？
![1547911306 1](https://user-images.githubusercontent.com/9164386/51428655-11e23480-1c41-11e9-9f4a-9a819ca91d56.png)

> 解决方法见文档
如果是分散的结构，如图(注2)，执行脚本的时候可能会出现错误：“合并可见图层”当前不可用。
可以了，感谢

**Comment by zs9024** [comment]
解决方法见文档
