### ISSUE TITLE
ps2017 脚本会报错  853行

### ISSUE THREAD

**Issue by loveAnimation** [zs9024/quick_psd2ugui#3]
psd.mergeVisibleLayers();  用新版本ps  不知道 这个函数被替换成什么了

**Comment by zs9024** [comment]
最近比较忙，我找时间修一下，你可以先试一下用cs6

**Comment by loveAnimation** [comment]
我使用cs6也是一样  会提示可用图层不能用  我直接复制  在复制一下psd然后调用合并图层  不会出错  但是在这个脚本里面就报错了   我给注释了就好了   问一下  这个合并的作用是什么   这里是要保存效果图吗？

**Comment by zs9024** [comment]
合并可见图层的作用就是切图和导出图片文件，报错应该是图层不能合并，你可以手动将该图层或图层组栅格化或转成智能对象，然后再运行脚本来切图。有些效果在制作的时候最好先手动合并了再切图，比如一个按钮背景，包含多个效果的图层（阴影，高光等），合并了就只会切一张图

**Comment by lyg2260123** [comment]
错误同楼上。赶脚这个工具能收费。

**Comment by markelion** [comment]
错误同楼上，使用的是cs6  ，导出图片时这一步psd.mergeVisibleLayers()都会报错“发生了常规PhotoShop错误，该功能可能无法在这个版本中的PhotoShop中使用”   求解决

目前只能通过屏蔽这句代码来解决，但不确定会不会有其他问题

**Comment by zs9024** [comment]
可以的话，发一份有问题的psd文件到我邮箱（252703974@qq.com），我看一下

**Comment by zs9024** [comment]
可以检查是否有单个图片(比如背景图)位于根节点的最后，并将其移到某个图层组下面，具体见文档

**Comment by markelion** [comment]
现在九宫切图貌似并没有起作用啊   切出来得九宫图还是原尺寸那么大
