### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by zikerlin** [zs9024/quick_psd2ugui#6]
Grid的範例 PSD輸出都會出現錯誤

**Comment by zs9024** [comment]
报什么错，哪一行？

**Comment by zikerlin** [comment]
都會出現附圖的錯誤

2017-10-22 20:18 GMT+08:00 waking_man <notifications@github.com>:

**Comment by zikerlin** [comment]
都會出現附圖的錯誤
![grid](https://user-images.githubusercontent.com/6878979/31985983-5fc0856e-b999-11e7-92f1-fdd1a51c7ebb.png)

**Comment by zs9024** [comment]
ps的版本是什么

**Comment by zikerlin** [comment]
psd cc 2017

2017-11-16 17:41 GMT+08:00 waking_man <notifications@github.com>:

**Comment by shenleon** [comment]
![image](https://user-images.githubusercontent.com/4394053/35601767-c380e4f4-066f-11e8-8291-c6ddfe2f7e5b.png)

**Comment by shenleon** [comment]
这里报错了，那个recSize未定义
但是不熟悉那个脚本语法，不会改，作者帮忙看看咧

**Comment by zs9024** [comment]
谢谢反馈，已修复
