### ISSUE TITLE
图片左右不对称切9宫格有问题

### ISSUE THREAD

**Issue by xieqixiang** [zs9024/quick_psd2ugui#9]
切出来的左边图片会往上移动一个像素。有空格。

**Comment by 503913873** [comment]
我也遇到了，偏移不止一像素。代码doc.paste复制出来的就会偏移，请问有找到解决方案吗？

**Comment by zs9024** [comment]
这种情况是有问题，待改

**Comment by qilinlee** [comment]
Unity中TextureImporter.spriteBorder的顺序是X=left, Y=bottom, Z=right, W=top。所以将PSDImportCtrl.cs文件第305行：
textureImporter.spriteBorder = new Vector4(float.Parse(args[0]), float.Parse(args[1]), float.Parse(args[2]), float.Parse(args[3]));
改为：
textureImporter.spriteBorder = new Vector4(float.Parse(args[0]), float.Parse(args[3]), float.Parse(args[2]), float.Parse(args[1]));
即可。

**Comment by zs9024** [comment]
fix了一发，可以试一下
